name: Peter Debelak
description: Posts about Ruby, Rails, and other technical topics from Peter Debelak
url: "https://www.peterdebelak.com"
author: Peter Debelak
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: "blog"
      layout: post
      active: blog
permalink: /:categories/:title/
paginate: 10
paginate_path: /blog/page:num/
url: "http://www.peterdebelak.com"
sass:
  sass_dir: css
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
