defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: "blog"
      layout: post
      active: blog
permalink: /:categories/:title/
paginate: 3
paginate_path: /blog/page:num/
url: "http://www.peterdebelak.com"
sass:
  sass_dir: css
  style: :compressed
gems:
  - jekyll-sitemap
